name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile Day 1
      run: g++ day1/*.cpp -o day1_app || echo "Skipping Day 1"

    - name: Compile Day 2
      run: g++ day2/*.cpp -o day2_app || echo "Skipping Day 2"

    - name: Compile Day 3
      run: g++ day3/*.cpp -o day3_app || echo "Skipping Day 3"

    - name: Compile Day 4
      run: g++ day4/*.cpp -o day4_app || echo "Skipping Day 4"

    - name: Compile Day 7 (Capstone)
      run: g++ day7/atm_system.cpp -o atm_app || echo "Skipping Day 7"
